const palette: Record<string, string> = {
  o: '#332c29',
  g: '#86ab59',
  G: '#4e743c',
  y: '#efd28a',
  b: '#75b6ce',
  B: '#416d91',
  r: '#cd6950',
  R: '#8e4036',
  w: '#eee5cc',
  s: '#aa9680',
  p: '#b38aae',
}

const sprites = {
  person: [
    '....yyy.....',
    '....yoy.....',
    '.....s......',
    '...bbbbb....',
    '...bbybb....',
    '...sbbb.s...',
    '....BBB.....',
    '....B.B.....',
    '...BB.BB....',
    '...oo.oo....',
  ],
  house: [
    '.....r......',
    '....rrr.....',
    '...rryrr....',
    '..rryyyrr...',
    '.RRRRRRRRR..',
    '..wywwwyw...',
    '..wBwwwBw...',
    '..wwwRwww...',
    '..wwwRwww...',
    '..sssssss...',
  ],
  mountain: [
    '......w.....',
    '.....www....',
    '....wswsw...',
    '...ssssss...',
    '..Gsssssss..',
    '.GGGsssssss.',
    'GGyGGssGsssG',
    'GGGGGGGGGGGG',
  ],
  apple: [
    '......GG....',
    '.....sG.....',
    '..rrr.rrr...',
    '.ryrrrrrrr..',
    '.ryrrrrrrr..',
    '.rrrrrrrrr..',
    '..rrrrrrR...',
    '...RRRRR....',
  ],
  map: [
    '.yyyywwyyyy.',
    '.ybbywwyGGy.',
    '.ybbywwGGGy.',
    '.yGGywwyGyy.',
    '.GGGywbyyyy.',
    '.yGyywbbyGy.',
    '.yyyywwyGGy.',
    '.yyyywwyyyy.',
  ],
  cursor: [
    '..w.........',
    '..ww........',
    '..wyw.......',
    '..wyyw......',
    '..wyyyw.....',
    '..wyyyyw....',
    '..wywwww....',
    '..wwyw......',
    '.....yw.....',
    '.....ww.....',
  ],
  plus: [
    '....yy......',
    '....yy......',
    '....yy......',
    '.yyyyyyyy...',
    '.yyyyyyyy...',
    '....yy......',
    '....yy......',
    '....yy......',
  ],
  tribe: [
    '..yyy.yyy...',
    '..yoy.yoy...',
    '...s...s....',
    '.bbbbbGGGGG.',
    '.bbybbGGyGG.',
    '..BBB.GGG...',
    '..B.B.G.G...',
    '.BB.BBG.GG..',
  ],
  heart: [
    '..ggg.ggg...',
    '.gyggggggg..',
    '.gyggggggg..',
    '.ggggggggg..',
    '..ggggggG...',
    '...ggggG....',
    '....ggG.....',
    '.....G......',
  ],
  skull: [
    '...wwwww....',
    '..wwwwwww...',
    '.wwwswwwww..',
    '.woowwooww..',
    '.woowwooww..',
    '..wwwowww...',
    '...wwwww....',
    '...w.w.w....',
  ],
  fire: [
    '.....r......',
    '.....ry.....',
    '...r.ryr....',
    '...ryyyr....',
    '..rryyyrr...',
    '.rryyyyyrr..',
    '.rryywyyrr..',
    '..rrwwwrr...',
    '...RRRRR....',
    '.sss..sss...',
  ],
  grass: [
    '..g...g.....',
    '...g.g..g...',
    '.g.ggg.g....',
    '..ggggggg...',
    '.GGGGGGGGG..',
    '.sssssssss..',
    '..sssssss...',
  ],
  water: [
    '............',
    '.bb...bb....',
    'bBBb.bBBb.b.',
    '...bb...bb..',
    '.bb...bb....',
    'bBBb.bBBb.b.',
    '...bb...bb..',
  ],
  rock: ['...sssss....', '..swwwsss...', '.swwssssss..', '.sssssssss..', '..ssssssso..', '...oooooo...'],
  sand: ['............', '....yyyy....', '..yyyyyyyy..', '.yyysyyysy..', '..yyyyyyy...', '...sssss....'],
  snow: [
    '.....w......',
    '..w..w..w...',
    '...w.w.w....',
    '....www.....',
    '.wwwwwwwww..',
    '....www.....',
    '...w.w.w....',
    '..w..w..w...',
    '.....w......',
  ],
  drop: [
    '.....b......',
    '....bbb.....',
    '....bbb.....',
    '...bwbbb....',
    '..bwwbbbb...',
    '..bwbbbbb...',
    '...bbBBB....',
    '....BBB.....',
  ],
  border: [
    '...yyyyy....',
    '..y.....y...',
    '.y.......y..',
    '.y..GGG..y..',
    '.y..GGG..y..',
    '.y.......y..',
    '..y.....y...',
    '...yyyyy....',
  ],
  swords: [
    '.w.......w..',
    '.ww.....ww..',
    '..ww...ww...',
    '...ww.ww....',
    '....www.....',
    '...ywwwy....',
    '..yyy.yyy...',
    '...s...s....',
    '..s.....s...',
  ],
  route: ['.yy.........', '...y........', '...y..yyyy..', '...yyyy..y..', '.........yy.'],
  compass: [
    '...yyyyy....',
    '..yswwwsy...',
    '.yswwrwwsy..',
    '.ywwwrwwwy..',
    '.ywwrrrwwy..',
    '.ywwwBwwwy..',
    '.yswwBwwsy..',
    '..yswwwsy...',
    '...yyyyy....',
  ],
  deer: [
    '..s.s...s.s.',
    '...ss...ss..',
    '....s...s...',
    '....sssss...',
    '....sosss...',
    '.ssssssss...',
    '.sssssss....',
    '..s..s......',
    '..s..s......',
  ],
  rabbit: [
    '....w.w.....',
    '....wpw.....',
    '....wpw.....',
    '....www.....',
    '...wwwow....',
    '.wwwwww.....',
    '.wwwwwww....',
    '..sssssss...',
  ],
  boar: ['...s...s....', '..sssssss...', '.ssssssoss..', '.sssssssyw..', '..sssssss...', '..s.s.s.s...'],
  wolf: [
    '...s...s....',
    '...ss.ss....',
    '...swsws....',
    '.sssssoos...',
    '.ssssssww...',
    '..ssssss....',
    '..s..s......',
  ],
  bird: ['.....bbb....', '....bwoby...', '..bbbbb.....', '.bBBBBb.....', '...bbb......', '....ss......'],
  fish: ['....bbbbb...', 'b..bwwbbbb..', 'bbbwwbbbob..', 'bbbBBBBBBB..', 'b..BBBBBB...', '....BBBB....'],
  rain: [
    '...wwwww....',
    '..wwwwwww...',
    '.sswwwwsss..',
    '.sssssssss..',
    '............',
    '..b..b..b...',
    '.b..b..b....',
  ],
  storm: [
    '...sssss....',
    '..sssssss...',
    '.BBBBBBBBB..',
    '....yy......',
    '...yy..b....',
    '....yyb.....',
    '...yy.......',
    '...y........',
  ],
  sun: [
    '.....y......',
    '..y.....y...',
    '....yyy.....',
    '...yyyyy....',
    '.y.yyyyy.y..',
    '...yyyyy....',
    '....yyy.....',
    '..y.....y...',
    '.....y......',
  ],
  drought: [
    '........y...',
    '...G...yyy..',
    '.G.G....y...',
    '.GGG........',
    '...G..yyy...',
    '.yyyyyyyyyy.',
    '..sss.ssss..',
  ],
  germ: [
    '..g..g..g...',
    '...ggggg....',
    '..gGggGgg...',
    '.ggggggggg..',
    '..ggGgggg...',
    '...ggggg....',
    '..g..g..g...',
  ],
  clock: [
    '....yyy.....',
    '.....y......',
    '...wwwww....',
    '..wwwwwBw...',
    '.wwwwwBwww..',
    '.wwwwwBBww..',
    '.wwwwwwwww..',
    '..wwwwwww...',
    '...sssss....',
  ],
  pause: [
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
    '..yyy.yyy...',
  ],
  play: [
    '...y........',
    '...yyy......',
    '...yyyyy....',
    '...yyyyyyy..',
    '...yyyyy....',
    '...yyy......',
    '...y........',
  ],
  fast: [
    '.y....y.....',
    '.yy...yy....',
    '.yyy..yyy...',
    '.yyyy.yyyy..',
    '.yyy..yyy...',
    '.yy...yy....',
    '.y....y.....',
  ],
  bolt: [
    '.....yyyy...',
    '....yyyy....',
    '...yyyy.....',
    '..yyyyyyy...',
    '.....yyy....',
    '....yyy.....',
    '...yy.......',
    '..y.........',
  ],
  turtle: ['...GGGGG....', '..GgGgGgG...', '..GGgGgGGgg.', '.gGgGgGgGgo.', '..GGGGGGG...', '..g.....g...'],
} satisfies Record<string, string[]>

const icons: Record<string, keyof typeof sprites> = {
  '🚶': 'person',
  '🏠': 'house',
  '🛖': 'house',
  '⛰️': 'mountain',
  '🍎': 'apple',
  '🗺️': 'map',
  '🖱️': 'cursor',
  '✚': 'plus',
  '👥': 'tribe',
  '💚': 'heart',
  '💀': 'skull',
  '🔥': 'fire',
  '🟩': 'grass',
  '🟦': 'water',
  '🪨': 'rock',
  '🟨': 'sand',
  '❄️': 'snow',
  '💧': 'drop',
  '⬡': 'border',
  '🏘️': 'house',
  '⚔️': 'swords',
  '〰️': 'route',
  '🧭': 'compass',
  '🦌': 'deer',
  '🐇': 'rabbit',
  '🐗': 'boar',
  '🐺': 'wolf',
  '🐦': 'bird',
  '🐟': 'fish',
  '🌧️': 'rain',
  '⛈️': 'storm',
  '☀️': 'sun',
  '🏜️': 'drought',
  '🌦️': 'rain',
  '🦠': 'germ',
  '⏱️': 'clock',
  '⏸️': 'pause',
  '▶️': 'play',
  '🐢': 'turtle',
  '⏩': 'fast',
  '⏭️': 'fast',
  '⚡': 'bolt',
}

export function ToolSprite({ icon }: { icon: string }) {
  const rows = sprites[icons[icon] ?? 'cursor']
  return (
    <svg
      width="24"
      height="24"
      viewBox="0 0 12 12"
      shapeRendering="crispEdges"
      aria-hidden="true"
      focusable="false"
      style={{ display: 'inline-block', verticalAlign: 'middle' }}
    >
      {rows.flatMap((row, y) =>
        [...row].flatMap((pixel, x) =>
          pixel === '.'
            ? []
            : [
                <rect
                  key={`${x}-${y}`}
                  x={x}
                  y={y + Math.floor((12 - rows.length) / 2)}
                  width="1"
                  height="1"
                  fill={palette[pixel]}
                />,
              ],
        ),
      )}
    </svg>
  )
}
